### ISSUE TITLE
Crashes with Steam on ArchLinux (please help me track down the cause)

### ISSUE THREAD

**Issue by nickguletskii** [nickguletskii/GLXOSD#15]
# Suspected cause #

libstdc++ version incompatibility

# Things to try #

Try changing `-std=c++11` to `-std=c++0x` in CMakeLists.txt, then `./clean` and follow the compilation instructions.

# Missing information #

Please provide the output of the following commands:

    ldd [PATH_TO_BOOST_SYSTEM_SO]

**Comment by lubosz** [comment]
I can reproduce this bug. I want to run GLXOSD with Cities:Skylines with following command:
`glxosd --steam steam steam://rungameid/255710`

I get following error several times:
`grep: /home/bmonkey/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /usr/lib/glxosd/libglxosd.so)`

Running it with `glxosd --steam %command%` out of steam does not work either.

Can I build glxosd without lm_sensors being a dependency? I am not sure if It can be cross compiled with m32.

I am using Arch Linux 64bit, with the following AUR Package: https://aur.archlinux.org/packages/glxosd-git/

**Comment by lubosz** [comment]
When I run stream with glxosd --steam I cannot see my listed games. Steam wants me to create a new Steam folder, since it cannot find one.

I managed to install a 32bit version of glxosd, just needed to package 
https://aur.archlinux.org/packages/lib32-glxosd-git/
https://aur.archlinux.org/packages/lib32-libxnvctrl/
https://aur.archlinux.org/packages/lib32-lm_sensors/

Not sure if i run it correctly though, I get
ERROR: ld.so: object 'libglxosd-elfhacks.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libglxosd-glinject.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.

When I try to run just steam.

**Comment by lubosz** [comment]
I think this is basically the problem why Steam cannot access the filesystem when run with glxosd:

´´´
$ grep GLIBCXX_3.4.20 /usr/lib/libstdc++.so.6
Binary file /usr/lib/libstdc++.so.6 matches
$ grep GLIBCXX_3.4.20 /home/bmonkey/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu/libstdc++.so.6
$ grep GLIBCXX_3.4.19 /home/bmonkey/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu/libstdc++.so.6
Binary file /home/bmonkey/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu/libstdc++.so.6 matches
´´´

**Comment by lubosz** [comment]
This hack fixes the issue for me:
```
$ mv /home/bmonkey/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.18 /home/bmonkey/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.18.old

$ ln -s /usr/lib/libstdc++.so.6.0.20 /home/bmonkey/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.18
```

**Comment by nickguletskii** [comment]
Possible cause: https://github.com/nickguletskii/GLXOSD/issues/24

**Comment by nickguletskii** [comment]
This issue is caused by the bundled libstdc++ binaries being older than the ones that GLXOSD was linked against. Please see [the according FAQ entry](http://glxosd.nickguletskii.com/faq.html#when-i-launch-an-application-with-glxosd-it-crashes-why).

If that is not the issue, please ask for this issue to be reopened.
