### ISSUE TITLE
How to run glxosd on Mint 17.3

### ISSUE THREAD

**Issue by mglinux** [nickguletskii/GLXOSD#79]
LM 17 is based on ubuntu 14.04 and glxosd supports 15+. From the ppa I can install v2.5 and it is working. I see fps and temperature but nothing else. Compiled v3 from source and all Sensors are working in glxgears but not running in games. Got several errors, tried to fix them but finally gave up. 

It seems v3 isnt in the ppa, so could you please add it?

**Comment by licaon-kter** [comment]
v3 is in the PPA for Wily and Xenial, maybe you need to update your APT list entry?

**Comment by mglinux** [comment]
ppa:nickguletskii200/glxosd

Used this one, update list was done. Opening the ppa it only shows 2.5. So I thought it is because of not running 15+ ubuntu

**Comment by licaon-kter** [comment]
https://launchpad.net/~nickguletskii200/+archive/ubuntu/glxosd
or
https://launchpad.net/~nickguletskii200/+archive/ubuntu/glxosd-experimental

**Comment by nickguletskii** [comment]
First of all, you should **never** add the glxosd-experimental ppa on a production. I use it to verify if the packages are ready to be released into the main repository. If a version is ready, it is in the main ppa.

Secondly, I haven't had the time to backport GLXOSD v3 to Trusty. I hope that I'll have a little bit more time next week, so I'll see what I can do about it.

Also, it didn't work in games because most games have 32 bit binaries and you were compiling on a 64 bit system, which gave you 64 bit binaries.

**Comment by mglinux** [comment]
Would be nice if you could backport it. THX for help!

**Comment by nickguletskii** [comment]
GLXOSD v3.1.1 is now available for Ubuntu 14.04 and later.
