### ISSUE TITLE
Please add this app to default Ubuntu/Debian repos

### ISSUE THREAD

**Issue by tim66** [nickguletskii/GLXOSD#80]

**Comment by licaon-kter** [comment]
Just add the PPA for Willy or Xenial. ;)

**Comment by tim66** [comment]
> Just add the PPA for Willy or Xenial. ;)
	
What's the point then in default repos if everyone will make their programs available in PPA only or in suggest download .exe file from 3d party site?

What the reason for PPA instead of standard repos? Need more time and work? I suggest then thank the author and make some donation.

**Comment by nickguletskii** [comment]
I think that to be in the Debian repositories, the packages have to meet certain quality standards. As of right now, GLXOSD has no man pages and there are many little things that have to be fixed before even considering adding it to any default repos.

Also, I am not sure that I want GLXOSD to be in the default repos for different distributions, because once a package is in stable repositories it is very hard to provide fixes for it. A ton of things can go wrong with GLXOSD and it is very hard to test, and considering how it takes many years for a new upstream version to get uploaded to Debian stable, it's probably not the place for GLXOSD.

**Comment by tim66** [comment]
Oh I something like this thought. Anyway thank for your work and useful app.
