### ISSUE TITLE
X error: GLXBadDrawable

### ISSUE THREAD

**Issue by tostiheld** [nickguletskii/GLXOSD#84]
When i start the application with

`glxosd glxgears`

i get the following error/output:

    X Error of failed request:  GLXBadDrawable
      Major opcode of failed request:  156 (GLX)
      Minor opcode of failed request:  29 (X_GLXGetDrawableAttributes)
      Serial number of failed request:  42
      Current serial number in output stream:  42

**Comment by licaon-kter** [comment]
OS version? Install method? Video driver?

**Comment by tostiheld** [comment]
Oops sorry haha i was in a hurry. OS is Debian Jessie 64 bit. Video driver is xorg-video-radeon or xf86-video-ati version 7.5.0. I installed it using the debian package repository found on the glxosd website

**Comment by nickguletskii** [comment]
This is strange because I only get this with Mesa drivers and that GLXGetDrawableAttributes is actually called when it is supposed to work. I actually spent quite a lot of time chasing this bug a few months ago, and at the end I figured that the issue was exclusive to older Intel drivers and Mesa drivers.

**Comment by nickguletskii** [comment]
Should be fixed with version 3.2.1.
